version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8081:8081
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  angular:
    container_name : angular
    build: ./frontend
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - springboot
  
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always
    
  springboot:
    container_name: springboot
    restart : always
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    volumes:
      - ./springboot:/springboot
      - ~/.m2:/root/.m2
    expose:
      - "8081: 8081"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker